#include <vtkSmartPointer.h>
#include <vtkXMLUnstructuredGridReader.h>
#include <vtkUnstructuredGrid.h>
#include <vtkPointData.h>
#include <vtkXMLUnstructuredGridWriter.h>

#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <corlib/UniqueFilename.hpp>
#include <iterator>

int main( int argc, char * argv[] )
{
    if( argc != 6 ) {
        std::cerr << "Usage: " << argv[0]
                  << " basename " 
                  << " XXXX (begin number string)" 
                  << " YYYY (end number string)"
                  << " shift "
                  << " deltaT "
                  << "  "
                  << std::endl;
        return EXIT_FAILURE;
    }

    std::string basename  = boost::lexical_cast<std::string>( argv[1] );

    const unsigned begin  = boost::lexical_cast<unsigned>( argv[2] );
    const unsigned end    = boost::lexical_cast<unsigned>( argv[3] );
    const unsigned inc    = boost::lexical_cast<unsigned>( argv[4] );
    const double   deltaT = boost::lexical_cast<double>(   argv[5] );
    const std::string endNumber = std::string( argv[2] );
    const unsigned numeralWidth = endNumber.size();

    int pointID        = -1;
    int pointDatum     = -1;
    int datumComponent = -1;
    std::string outFileName;

    for ( unsigned step = begin; step <= end; step += inc ) {

        // generate the filename
        std::string filename = corlib::UniqueFilename( numeralWidth )( basename, step, "vtu" );

        //read XML vtu file
        vtkSmartPointer<vtkXMLUnstructuredGridReader> reader =
            vtkSmartPointer<vtkXMLUnstructuredGridReader>::New();
        reader -> SetFileName( filename.c_str() );
        reader -> Update();

        // get access to the unstructured grid
        vtkSmartPointer<vtkUnstructuredGrid> unstructuredGrid = reader -> GetOutput();

        // point data
        vtkSmartPointer<vtkPointData> pointData =  unstructuredGrid -> GetPointData();

        // ask info about point datum
        if ( step == begin ) {
            // choose point
            const unsigned numPoints = unstructuredGrid -> GetNumberOfPoints();
            std::cout << "Choose point ID from 0 to " << numPoints - 1 << ": ";
            std::cin >> pointID;

            // write coordinates out
            double * point = unstructuredGrid -> GetPoint( pointID );
            std::cout << point[0] << "  " << point[1] << "  " << point[2] << std::endl;

            // choose datum
            std::cout << "Choose point datum from " << std::endl;
            const unsigned numPointDataArrays = pointData -> GetNumberOfArrays();
            for ( unsigned na = 0; na < numPointDataArrays; na ++ ) {
                const std::string dataName = ( pointData -> GetArray( na ) ) -> GetName();
                std::cout << "  " << na << ": " << dataName << std::endl;
            }
            std::cin >> pointDatum;

            // choose component
            const unsigned numArrayComponents = ( pointData -> GetArray( pointDatum ) ) -> GetNumberOfComponents();
            if ( numArrayComponents > 1 ) {
                std::cout << " Choose component from 0 to " << numArrayComponents - 1 << ": ";
                std::cin  >> datumComponent;
            }
            else datumComponent = 0;

            
            const std::string dataName = ( pointData -> GetArray( pointDatum ) ) -> GetName();
            outFileName = corlib::UniqueFilename(4,1)( dataName, pointID, datumComponent, "dat" );
            std::ofstream out( outFileName.c_str() );
            out << "# Generated by " << argv[0] << " with arguments: ";
            std::copy( argv+1, argv+argc, std::ostream_iterator<std::string>( out, "  " ) );
            out << std::endl;
            out.close();
        }

        // extract datum 
        vtkSmartPointer<vtkDataArray> field = pointData -> GetArray( pointDatum );
        double * tuple = field -> GetTuple( pointID );
        
        std::ofstream out( outFileName.c_str(), std::ios_base::app );
        out << boost::format( "%1% %|15t|%2% \n" ) % (step * deltaT) %tuple[datumComponent];
        out.close();

    }

    return 0;
}
