#include <vtkSmartPointer.h>
#include <vtkXMLPolyDataReader.h>
#include <vtkXMLUnstructuredGridReader.h>
#include <vtkPointData.h>
#include <vtkPolyData.h>
#include <vtkUnstructuredGrid.h>
#include <vtkCellDerivatives.h>
#include <vtkCellDataToPointData.h>
#include <vtkXMLPolyDataWriter.h>
#include <vtkXMLUnstructuredGridWriter.h>

#include <string>
#include <boost/lexical_cast.hpp>

//------------------------------------------------------------------------------
//                Add vorticity to the point data
//------------------------------------------------------------------------------
// Note: In case of 2D unstructured grids, the vtkCellDerivatives filter does
//       not work properly. Therefore, the file has to be first converted to
//       a PolyData file using the 'vtu2vtp' converter. This should not be 
//       necessary in 3D nor in case of a structured (rectilinear) mesh.
//------------------------------------------------------------------------------
int main(int argc, char *argv[])
{
    //define usage
    if ( (argc < 2) or (argc > 3) ){
        std::cerr << "Usage: " << argv[0] << " filename.vt[up]  [poly]" << std::endl
                  << "   where poly={0,1} (default=0) indicates that a polydata file is " << std::endl
                  << "   read (needed for 2D unstructured meshes, generated by vtu2vtp)." << std::endl;
        return EXIT_FAILURE;
    }

    // read command line
    const std::string filename = boost::lexical_cast<std::string>( argv[1] );
    const bool        poly     = (argc == 2 ? 0 : boost::lexical_cast<bool>( argv[2] ) );
    
 
    // set up a reader
    vtkSmartPointer<vtkXMLPolyDataReader>         polyReader = vtkSmartPointer<vtkXMLPolyDataReader>::New();
    vtkSmartPointer<vtkXMLUnstructuredGridReader> gridReader = vtkSmartPointer<vtkXMLUnstructuredGridReader>::New();

    vtkSmartPointer<vtkPointData> pointData;

    if ( poly ) {
        polyReader -> SetFileName( filename.c_str() );
        polyReader -> Update();
        pointData = (polyReader -> GetOutput()) -> GetPointData();
    }
    else {
        gridReader -> SetFileName( filename.c_str() );
        gridReader -> Update();
        pointData = (gridReader -> GetOutput()) -> GetPointData();
    }

    const unsigned nArrays = pointData -> GetNumberOfArrays();
    vtkstd::string vectorName;
    bool found = false;

    for ( unsigned array = 0; array < nArrays; array ++ ) {

        // found first field with 3 components -> the vector field
        if (pointData -> GetArray( array ) -> GetNumberOfComponents() == 3 ) {
            vectorName = pointData -> GetArrayName( array );
            found = true;
            break;
        }
        
    }

    // a vector field is mandatory
    if ( not found ) {
        vtkstd::cout << " No vector field found!! " << vtkstd::endl;
        return EXIT_FAILURE;
    }

    vtkstd::cout << " Computing vorticity field based on " << vectorName << vtkstd::endl;

    // compute cell derivatives
    vtkSmartPointer<vtkCellDerivatives> cellDeriv = vtkSmartPointer<vtkCellDerivatives>::New();
    cellDeriv -> SetVectorModeToComputeVorticity();
    cellDeriv -> SetTensorModeToComputeGradient();

    if ( poly ) {
        cellDeriv -> SetInput( polyReader -> GetOutput() );
    }
    else {
        cellDeriv -> SetInput( gridReader -> GetOutput() );
    }
    cellDeriv -> SetInputArrayToProcess( 1,0,0,vtkDataObject::FIELD_ASSOCIATION_POINTS, vectorName.c_str() );
    cellDeriv -> Update();

    // pass computed data to points
    vtkSmartPointer<vtkCellDataToPointData> cell2point = vtkSmartPointer<vtkCellDataToPointData>::New();
    cell2point -> SetInputConnection( 0, cellDeriv -> GetOutputPort(0) );
    cell2point -> Update();

    // write data back to same file
    vtkSmartPointer<vtkXMLWriter> writer;
    if ( poly ) writer = vtkSmartPointer<vtkXMLPolyDataWriter>::New();
    else        writer = vtkSmartPointer<vtkXMLUnstructuredGridWriter>::New();
    writer -> SetFileName(filename.c_str() );
    writer -> SetInput( cell2point -> GetOutput() );
    writer -> SetDataModeToAppended();
    writer -> EncodeAppendedDataOff();
    writer -> Write();

    return 0;
}
