#include <string>
#include <iostream>
#include <vector>
#include <cassert>
#include <sstream>
//------------------------------------------------------------------------------
#include <vtkSmartPointer.h>
#include <vtkXMLStructuredGridReader.h>
#include <vtkStructuredGrid.h>
#include <vtkPoints.h>
#include <vtkPointData.h>
#include <vtkCellData.h>
#include <vtkIdList.h>
//------------------------------------------------------------------------------
#include <boost/lexical_cast.hpp>
#include <corlib/verify.hpp>
//------------------------------------------------------------------------------
#include "TECIO.h"

// make a name out of first character and component number
std::string makeName( std::string name, unsigned comp )
{
    std::stringstream aux;
    aux << name[0];
    if ( name.size() > 1 ) aux << name[1];
    if ( name.size() > 2 ) aux << name[2];
    if ( name.size() > 3 ) aux << name[3];
    aux << comp ;
    return aux.str();
}

//------------------------------------------------------------------------------
int main(int argc, char *argv[])
{
    //parse command line arguments
    if( argc != 2 ) {
        std::cerr << "Usage: " << argv[0]
                  << " filename.vts" << std::endl;
        return EXIT_FAILURE;
    }
 
    // file names
    const std::string filename       = boost::lexical_cast<std::string>( argv[1] );
    const std::string basename       = filename.substr( 0, filename.find( ".vts" ) );
    const std::string binaryOut      = basename + ".plt";
 
    //read XML vts file
    vtkSmartPointer<vtkXMLStructuredGridReader> reader =
        vtkSmartPointer<vtkXMLStructuredGridReader>::New();
    reader -> SetFileName( filename.c_str() );
    reader -> Update();

    // get access to the unstructured grid
    vtkSmartPointer<vtkStructuredGrid> structuredGrid = reader -> GetOutput();

    // get header data
    int iMin, iMax, jMin, jMax, kMin, kMax;
    structuredGrid -> GetExtent( iMin, iMax, jMin, jMax, kMin, kMax );
    const unsigned numI = iMax - iMin + 1;
    const unsigned numJ = jMax - jMin + 1;
    const unsigned numK = kMax - kMin + 1;
    const unsigned numPoints = structuredGrid -> GetNumberOfPoints();

    // point data
    vtkSmartPointer<vtkPointData> pointData =  structuredGrid -> GetPointData();
    const unsigned numPointDataArrays       = pointData -> GetNumberOfArrays();

    // access to points
    vtkSmartPointer<vtkPoints> points = structuredGrid -> GetPoints();

    //cell data
    vtkSmartPointer<vtkCellData> cellData =  structuredGrid -> GetCellData();
    const unsigned numCellDataArrays     = cellData -> GetNumberOfArrays();

    // generate data header string
    std::string dataHeader = "X  Y  Z ";
    std::vector<INTEGER4> varLocation(3,static_cast<INTEGER4>(1));
    for ( unsigned na = 0; na < numPointDataArrays; na ++ ) {
        const std::string dataName = ( pointData -> GetArray( na ) ) -> GetName();
        const unsigned numArrayComponents = ( pointData -> GetArray( na ) ) -> GetNumberOfComponents();
        for ( unsigned nc = 0; nc < numArrayComponents; nc ++ ) {
            const std::string appendix = makeName( dataName, nc ) + "  ";
            dataHeader.append( appendix );
            varLocation.push_back(static_cast<INTEGER4>(1));
        }
    }
    for ( unsigned na = 0; na < numCellDataArrays; na ++ ) {
        const std::string dataName = ( cellData -> GetArray( na ) ) -> GetName();
        const unsigned numArrayComponents = ( cellData -> GetArray( na ) ) -> GetNumberOfComponents();
        for ( unsigned nc = 0; nc < numArrayComponents; nc ++ ) {
            const std::string appendix = makeName( dataName, nc ) + "  ";
            dataHeader.append( appendix );
            varLocation.push_back(static_cast<INTEGER4>(0));
        }
    }
    std::cout << dataHeader << std::endl;
    
    //--------------------------------------------------------------------------
    // HEADER 
    INTEGER4 fieldFileType = 0; //!< FULL (i.e. Grid + Solution)
    INTEGER4 debug         = 1; //!< No debugging
    INTEGER4 vIsDouble     = 0; //!< Single precision

    // open and initialize binary file
    INTEGER4 I = TECINI112( (char*)"Generated by vtu2tec", //!< Message
                            (char*)dataHeader.c_str(),     //!< Variables names
                            (char*)binaryOut.c_str(),      //!< Output file name
                            (char*)".",                    //!< Scratch file directory
                            &fieldFileType,                
                            &debug,
                            &vIsDouble );
    FTL_VERIFY( I == 0 );

    //--------------------------------------------------------------------------
    // ZONE
    INTEGER4 zT = 0;                //!< Ordered data (structured grid!)
    INTEGER4 nI = numI;             //!< X-extent
    INTEGER4 nJ = numJ;             //!< Y-extent
    INTEGER4 nK = numK;             //!< Z-extent
    
    INTEGER4 dummyInt   = 0;
    double   dummyFloat = 0.0;
    INTEGER4 isBlock    = 1;

    I = TECZNE112((char*)"Zone 1",
                  &zT,
                  &nI,       &nJ,       &nK,
                  &dummyInt, &dummyInt, &dummyInt, //!< IJKCellMax    (0)
                  &dummyFloat,                     //!< Solution time (0.0)
                  &dummyInt,                       //!< Strand ID     (0)
                  &dummyInt,                       //!< ParentZoneID  (0)
                  &isBlock,                        //!< Block format mandatory (1)
                  &dummyInt, &dummyInt,            //!< NumFaceConnections/FaceNeighbor
                  &dummyInt, &dummyInt, &dummyInt, //!< FE-only (0,0,0)
                  NULL,      /* PassiveVarList */
                  &(varLocation[0]),  /* ValueLocation */
                  NULL,
                  &dummyInt); //! Don't share

    //--------------------------------------------------------------------------
    // write coordinates
    std::vector<double> X, Y, Z;
    for ( unsigned np = 0; np < numPoints; np ++ ) {
        // coordinates
        double xyz[3];
        points -> GetPoint( np, xyz );
        X.push_back( xyz[0] );
        Y.push_back( xyz[1] );
        Z.push_back( xyz[2] );
    }
    INTEGER4 isDouble = 1;
    INTEGER4 nP       = numPoints;
    I   = TECDAT112(&nP, &(X[0]), &isDouble); FTL_VERIFY( I == 0 );
    I   = TECDAT112(&nP, &(Y[0]), &isDouble); FTL_VERIFY( I == 0 );
    I   = TECDAT112(&nP, &(Z[0]), &isDouble); FTL_VERIFY( I == 0 );


    //--------------------------------------------------------------------------
    // write point data
    for ( unsigned na = 0; na < numPointDataArrays; na ++ ) {
        vtkSmartPointer<vtkDataArray> array = pointData -> GetArray( na );
        const unsigned numArrayComponents = array -> GetNumberOfComponents();
        for ( unsigned nc = 0; nc < numArrayComponents; nc ++ ) {
            std::vector<double> data;
            for ( unsigned np = 0; np < numPoints; np ++ ) {
                std::vector<double> datum( numArrayComponents );
                array -> GetTuple( np, &(datum[0]) );
                data.push_back( datum[nc] );
            }
            I = TECDAT112( &nP, &(data[0]), &isDouble ); FTL_VERIFY( I == 0 );
        }
    }

    //--------------------------------------------------------------------------
    // write cell data
    const unsigned numCells = structuredGrid -> GetNumberOfCells();
    INTEGER4 nC             = numCells;

    for ( unsigned na = 0; na < numCellDataArrays; na ++ ) {
        vtkSmartPointer<vtkDataArray> array = cellData -> GetArray( na );
        const unsigned numArrayComponents = array -> GetNumberOfComponents();
        for ( unsigned nc = 0; nc < numArrayComponents; nc ++ ) {
            std::vector<double> data;
            for ( unsigned ncell = 0; ncell < numCells; ncell ++ ) {
                std::vector<double> datum( numArrayComponents );
                array -> GetTuple( ncell, &(datum[0]) );
                data.push_back( datum[nc] );
            }
            I = TECDAT112( &nC, &(data[0]), &isDouble ); FTL_VERIFY( I == 0 );
        }
    }

    //--------------------------------------------------------------------------
    // terminate file io
    I = TECEND112(); FTL_VERIFY( I == 0 );

    return EXIT_SUCCESS;
}

 
