// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//
//                 Computational Structural Mechanics Lab
//                         University of Cambridge
//
// This software is copyrighted and all rights are retained by the University of
// Cambridge. All use, disclosure, and/or reproduction of any part not expressly
// authorised by the University of Cambridge is prohibited. (C) 2010 --
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

//! @file NormalSampler.hpp

#ifndef statX_infer_normalsampler_h
#define statX_infer_normalsampler_h

#include <random>

#include <Eigen/Core>

#include <corlib/verify.hpp>


//------------------------------------------------------------------------------
namespace statX {
    namespace infer {
        class NormalSampler;
    }
}

//------------------------------------------------------------------------------
/** \brief Wrapper for sampling from a uni- and multi- variate normal distribution
  * \details
  *
  * For a given mean and covariance matrix the sample is generated by multiplying
  * a white noise covariance with the cholesky decomposition of the given covariance
  * matrix.
  *
  */
class statX::infer::NormalSampler
{
public:
    NormalSampler ( const unsigned seed = std::random_device( )( ) )
            : generator_( seed )
    { }

    void giveSample ( const Eigen::VectorXd & mean,
                      const Eigen::MatrixXd & covMat,
                      Eigen::VectorXd & sampleVec )
    {

        FTL_VERIFY( mean.rows( ) == covMat.cols( ) );

        // Cholesky decomposition of the covariance matrix CovMat = L L^T
        Eigen::LLT < Eigen::MatrixXd > lltOfMk( covMat );
        Eigen::MatrixXd covMatL = lltOfMk.matrixL( );

        // Random generation from the white noise N( 0, 1 )
        std::normal_distribution<double> norm( 0., 1. );

        Eigen::VectorXd vNorm;
        vNorm.resize( mean.rows( ) );

        for ( size_t i = 0; i < mean.rows( ); ++ i ) {
            vNorm[ i ] = norm( generator_ );
        }

        // y = mean + L * N( 0, 1 )
        Eigen::VectorXd vNormK = covMatL * vNorm;
        sampleVec = mean + vNormK;

        return;
    }
      
    void writeSample ( const Eigen::VectorXd & mean,
                       const Eigen::MatrixXd & covMat, std::ostream & file,
                       unsigned numSamples = 1 )
    {

        FTL_VERIFY( numSamples >= 1 );

        // sampleMat has the size of (sensor number) x (sample number)
        Eigen::MatrixXd sampleMat( mean.rows( ), numSamples );
        for ( auto i = 0; i < numSamples; ++ i ) {
            Eigen::VectorXd sampleVec;
            giveSample( mean, covMat, sampleVec );
            sampleMat.col( i ) = sampleVec;
        }

        file << sampleMat.rows( ) << " " << sampleMat.cols( ) << std::endl;
        for ( auto j = 0; j < mean.rows( ); ++ j ) {
            for ( auto i = 0; i < numSamples; ++ i ) {
                file << sampleMat( j, i ) << " ";
            }
            file << '\n';
        }
    } 

private:
    std::mt19937 generator_;
};


#endif
